-- Auto-generated seed data
DELETE FROM checklist WHERE seeded=1;
DELETE FROM people;
DELETE FROM segments;

INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d1-welcome',1,'09:00','12:00','Welcome & morning tours','Emek HaTzvaim · Botanical Garden · Ein Yael','Participants split across three nature/culture sites of Jerusalem for guided morning tours.','open',0,0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d1-welcome','Decide: JF guides vs. our own guides for tours',0,1,0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d1-welcome','Confirm Emek HaTzvaim / Botanical Garden / Ein Yael tour logistics',0,1,1);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d1-lunch',1,'12:30','14:00','Lunch at Ein Yael','Ein Yael','Group lunch on site.','open',1,1);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d1-plenary',1,'14:00','16:00','Afternoon plenary — Jerusalem''s rich past','Theatre (Karon Hall)','Opening remarks by Erik Grabelsky. 75-min panel on successful Jerusalem institutions — their work and journey from the start (with images).','progress',0,2);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d1-plenary','Erik Grabelsky (opening)',1);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d1-plenary','Meirav Maor',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d1-plenary','Maya HaLevi',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d1-plenary','Sharon (Jerusalem Theatre)',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d1-plenary','Sigalit (Zoo)',0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d1-plenary','Confirm panel moderator (TBC)',0,1,0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d1-plenary','Collect panelist images / journey materials',0,1,1);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d1-hotel1',1,'16:30','18:30','Hotel settle-in time','Hotels','Free / organizing time at hotels.','confirmed',0,3);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d1-opening',1,'19:00','21:00','Opening event + show + chef dinner + keynote','Jerusalem Theatre','Opening ceremony with performance, chef''s dinner, and central speaker (Daniel Hagari).','progress',1,4);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d1-opening','Daniel Hagari (keynote)',0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d1-opening','Lock performance / show act',0,1,0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d1-opening','Confirm chef dinner menu & catering',0,1,1);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d1-night',1,'21:30','23:00','Night gathering at Mishkenot Sha''ananim','Mishkenot Sha''ananim','Whisky and music — relaxed networking under the open sky.','progress',0,5);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d1-night','Confirm whisky & music setup',0,1,0);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d2-run',2,'07:30','08:30','Running tour / yoga (optional)','TBC','Optional morning activity.','open',0,6);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d2-run','Decide running route / yoga provider & venue',0,1,0);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d2-leadership',2,'09:30','12:30','Morning — Shai Doron Leadership Program','Mishkenot Sha''ananim','Greetings by Mayor Moshe Lion. Keynote: Shapira / Goldberg-Polin family. Donors rotate across three stations meeting three leaders each for intimate dialogue + Q&A.','progress',0,7);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Mayor Moshe Lion (greeting)',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Shapira / Goldberg-Polin family (keynote)',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Keren Applebaum-Reef',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Daoud Alian',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Yaffa Buso',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Yehuda Cohen',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Fadi Dukaidek',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Neta Meisels',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Meredith Rothbart',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Daniela Zalcer',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Uri Tzadok',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Mohammed Zahar',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-leadership','Mishy Harman',0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d2-leadership','Confirm moderator (TBC)',0,1,0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d2-leadership','Design 3-station rotation logistics',0,1,1);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d2-lunch',2,'13:00','14:30','Lunch at Gan Yael','Gan Yael','Group lunch.','open',1,8);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d2-beithanina',2,'15:30','17:00','Site tour — Beit Hanina community center + Arabic lesson','Beit Hanina Sports Complex','Guided tour of new sports complex, then panel on social/civic/economic challenges facing East Jerusalem communities. Ends with an Arabic lesson by Gilad Sweet with an East Jerusalem partner.','progress',0,9);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-beithanina','Yerushalmit speakers',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-beithanina','Mira (Foundation)',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-beithanina','Wasim Elhaj (Beit Hanina complex CEO)',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-beithanina','Suleiman Maswadeh (journalist, moderator)',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d2-beithanina','Gilad Sweet (Arabic lesson)',0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d2-beithanina','Coordinate Gilad Sweet Arabic lesson + EJ partner',0,1,0);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d2-hotel',2,'17:30','19:30','Hotel settle-in time','Hotels','Free / organizing time.','confirmed',0,10);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d2-dinner',2,'20:00','22:00','Rooftop dinner at Artists'' Studios — Shipudei Ezra','Shipudei Ezra (Artists'' Studios rooftop)','Rooftop dinner + tour of artist studios, meeting a cluster of artists and 4-5 art/design stalls for donors to purchase pieces.','progress',1,11);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d2-dinner','Confirm Shipudei Ezra rooftop catering',0,1,0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d2-dinner','Curate 4-5 art/design stalls + artists',0,1,1);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d2-dinner','Set up purchase / payment flow for donors',0,1,2);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d2-night',2,'22:00','00:00','Night at Mishkenot / alt. Distillery music option','Mishkenot Sha''ananim / HaMazkeka','Whisky and music networking, or alternative culture/music experience at the Distillery as part of the Zikuk Festival happening the same date.','open',0,12);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d2-night','Decide Mishkenot vs. Distillery/Zikuk Festival option',0,1,0);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d3-run',3,'07:30','08:30','Running tour / yoga (optional)','TBC','Optional morning activity.','open',0,13);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d3-run','Decide running route / yoga provider & venue',0,1,0);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d3-morning',3,'09:30','13:00','Morning: Map of Jerusalem''s activity future — at the Mifal','The Mifal','Opening words by Erik Grabelsky. ''Field of Action / Activities Market'' — donors meet tables & stands of Jerusalem organizations, learn their impact, build future partnerships.','progress',0,14);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d3-morning','Erik Grabelsky (opening)',1);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d3-morning','Curate participating Jerusalem organizations',0,1,0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d3-morning','Design ''Field of Action'' table layout',0,1,1);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d3-lunch',3,'13:00','14:30','Lunch at the Mifal (street food stalls)','The Mifal','Street food stalls lunch.','open',1,15);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d3-lunch','Book street food vendors',0,1,0);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d3-thinktank',3,'15:00','17:30','Think tank at Science Museum: ''Manifest Future Jerusalem''','Science Museum','Interactive collaborative process bringing Jerusalem leaders and donors together to generate ideas, share strategies and shape the city''s next chapter.','progress',0,16);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d3-thinktank','Design interactive think-tank format & facilitation',0,1,0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d3-thinktank','Review attached detail doc (Google Drive)',0,1,1);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d3-hotel',3,'18:00','19:00','Hotel settle-in time','Hotels','Free / organizing time.','confirmed',0,17);
INSERT INTO segments (id,day,time,end_time,title,venue,descr,status,is_meal,sort_order) VALUES ('d3-gala',3,'20:00','00:00','Closing gala dinner at Tower of David','Tower of David','Closing remarks by Erik Grabelsky. Greeting by President (Bougie Herzog). Concert by Jerusalem East & West Orchestra conducted by Maestro Tom Cohen or Tahrir. Festive farewell whisky at the theatre.','progress',1,18);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d3-gala','Erik Grabelsky (closing)',1);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d3-gala','President Isaac (Bougie) Herzog (greeting)',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d3-gala','Maestro Tom Cohen / Tahrir (conductor)',0);
INSERT INTO people (segment_id,name,confirmed) VALUES ('d3-gala','Jerusalem East & West Orchestra',0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d3-gala','Confirm President Herzog attendance & protocol',0,1,0);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d3-gala','Confirm orchestra + conductor (Tom Cohen or Tahrir)',0,1,1);
INSERT INTO checklist (segment_id,text,done,seeded,sort_order) VALUES ('d3-gala','Lock gala catering at Tower of David',0,1,2);
